version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: foyer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  discovery-service:
    image: nourhenedahmeni/discovery-service:latest
    container_name: discovery-service
    ports:
      - "8095:8095"
    environment:
      SPRING_APPLICATION_NAME: DiscoveryServer
      SERVER_PORT: 8095
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_SERVER_ENABLE_SELF_PRESERVATION: "false"
      EUREKA_SERVER_PEER_NODE_CONNECT_TIMEOUT_MS: 1
      EUREKA_SERVER_PEER_NODE_READ_TIMEOUT_MS: 1
      EUREKA_SERVER_PEER_NODE_TOTAL_CONNECTIONS: 1
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"

  foyer-app:
    image: nourhenedahmeni/foyer-app:latest
    depends_on:
      - mysql
      - discovery-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8095/eureka/
      SPRING_APPLICATION_NAME: foyer-app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-storage:
