version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: foyer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - foyer-net

  discovery-service:
    build: ./DiscoveryServer
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - foyer-net

  api-gateway:
    build: ./ApiGateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - foyer-net
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=api-gateway

  foyer-app:
    build: ./Foyer2425-main
    container_name: foyer-app
    ports:
      - "9090:9090"
    depends_on:
      - mysql
      - discovery-service
    networks:
      - foyer-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foyer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=foyer-app

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    networks:
      - foyer-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - foyer-net

networks:
  foyer-net:
    driver: bridge
